technical_name = "hotel_reservations"
display_name = "Reservas Hoteleras"
component_type = "module"
package_type = "extension"
domain = "hospitality"
python = ">=3.11"
erp_version = ">=0.1.0"
version = "0.1.0"
license = "MIT"
description = "Sistema mínimo de reservas para hoteles"
authors = [{"name": "ERP NEXUS Team", "role": "author", "email": "dev@erp-nexus.org"}]